name: workspace deployment | UAT

on: 
    push:
        branches: [ workspace_publish ]
jobs:
    release:
        # You also can use the self-hosted runners.
        runs-on: windows-latest
        steps:
        # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
           - uses: actions/checkout@v2
           - uses: Azure/Synapse-workspace-deployment@V1.7.0
             with:
                  TargetWorkspaceName: 'mysynapse-uat'
                  TemplateFile: './synapse-deve/TemplateForWorkspace.json'
                  ParametersFile: './synapse-deve/TemplateParametersForWorkspace.json'
                  environment: 'Azure Public'
                  resourceGroup: 'SynapseCICD'
                  clientId: ${{secrets.CLIENT_ID}}
                  clientSecret:  'd9e5f657-42e3-4c84-94e5-5942f4eb7e2a'
                  subscriptionId: ${{secrets.SUBSCRIPTION_ID}}
                  tenantId: ${{secrets.TENANT_ID}}
         
      
